export const videoConstants = {
  LOADING: "VIDEO_LOADING",
  GET_VIDEOS: "GET_VIDEOS",
  GET_VIDEO: "GET_VIDEO",
  ERROR: "VIDEO_ERROR",
};

export const likeConstants = {
  LOADING: "LIKED_LOADING",
  GET_LIKED: "GET_LIKED",
  ERROR: "LIKE_ERROR",
  ADD_TO_LIKED: "ADD_TO_LIKED",
  REMOVE_FROM_LIKED: "REMOVE_FROM_LIKED",
};

export const watchLaterConstants = {
  LOADING: "WATCH_LATER_LOADING",
  GET_WATCH_LATER: "GET_WATCH_LATER",
  ERROR: "WATCH_LATER_ERROR",
  ADD_TO_WATCH_LATER: "ADD_TO_WATCH_LATER",
  REMOVE_FROM_WATCH_LATER: "REMOVE_FROM_WATCH_LATER",
};

export const historyConstants = {
  LOADING: "HISTORY_LOADING",
  GET_HISTORY: "GET_HISTORY",
  ERROR: "HISTORY_ERROR",
  ADD_TO_HISTORY: "ADD_TO_HISTORY",
  REMOVE_FROM_HISTORY: "REMOVE_FROM_HISTORY",
  CLEAR_HISTORY: "CLEAR_HISTORY",
};


export const playlistConstants = {
  LOADING: "PLAYLIST_LOADING",
  GET_PLAYLIST: "GET_PLAYLIST",
  ERROR: "PLAYLIST_ERROR",
  CREATE_PLAYLIST: "CREATE_PLAYLIST",
  DELETE_PLAYLIST: "DELETE_PLAYLIST",
  ADD_TO_PLAYLIST: "ADD_TO_PLAYLIST",
  REMOVE_FROM_PLAYLIST: "REMOVE_FROM_PLAYLIST",
};
