export const videoConstants = {
  LOADING: "VIDEO_LOADING",
  GET_VIDEOS: "GET_VIDEOS",
  GET_VIDEO: "GET_VIDEO",
  GET_CATEGORIES: "GET_CATEGORIES",
  ERROR: "VIDEO_ERROR",
  FILTER_CATEGORY: "FILTER_CATEGORY",
  FILTER_BY_TIME: " FILTER_BY_TIME",
  SEARCH: "SEARCH_VIDEO",
};

export const likeConstants = {
  LOADING: "LIKED_LOADING",
  GET_LIKED: "GET_LIKED",
  ERROR: "LIKE_ERROR",
  ADD_TO_LIKED: "ADD_TO_LIKED",
  REMOVE_FROM_LIKED: "REMOVE_FROM_LIKED",
};

export const watchLaterConstants = {
  LOADING: "WATCH_LATER_LOADING",
  GET_WATCH_LATER: "GET_WATCH_LATER",
  ERROR: "WATCH_LATER_ERROR",
  ADD_TO_WATCH_LATER: "ADD_TO_WATCH_LATER",
  REMOVE_FROM_WATCH_LATER: "REMOVE_FROM_WATCH_LATER",
};

export const historyConstants = {
  LOADING: "HISTORY_LOADING",
  GET_HISTORY: "GET_HISTORY",
  ERROR: "HISTORY_ERROR",
  ADD_TO_HISTORY: "ADD_TO_HISTORY",
  REMOVE_FROM_HISTORY: "REMOVE_FROM_HISTORY",
  CLEAR_HISTORY: "CLEAR_HISTORY",
};


export const playlistConstants = {
  LOADING: "PLAYLIST_LOADING",
  GET_PLAYLIST: "GET_PLAYLISTS",
  ERROR: "PLAYLIST_ERROR",
  CREATE_PLAYLIST: "CREATE_PLAYLIST",
  DELETE_PLAYLIST: "DELETE_PLAYLIST",
  ADD_TO_PLAYLIST: "ADD_TO_PLAYLIST",
  REMOVE_FROM_PLAYLIST: "REMOVE_FROM_PLAYLIST",
  OPEN_MODAL: "OPEN_PLAYLIST_MODAL",
  CLOSE_MODAL: "CLOSE_PLAYLIST_MODAL",
};

export const notesConstants = {
  LOADING: "NOTES_LOADING",
  GET_NOTES: "GET_NOTES",
  ERROR: "NOTES_ERROR",
  CREATE_NOTE: "CREATE_NOTE",
  UPDATE_NOTE: "UPDATE_NOTE",
  DELETE_NOTE: "DELETE_NOTE",
  DELETE_ALL_NOTES: "DELETE_ALL_NOTES",
};