export const videos = [
  {
    _id: "eNtv1_8MQds",
    title: "How to draw a Manga Page | Drawlikeasir",
    description: "",
    categoryName: "Manga",
    creator: "Drawlikeasir",
  },
  {
    _id: "m583-GDIFCQ",
    title: "HOW TO DRAW MUSCLES IN 10 MINUTES",
    creator: "Drawlikeasir",
    categoryName: "Manga, Anatomy",
    description: "",
  },
  {
    _id: "5W3Wj-a_7Vo",
    title: "How to DRAW FACES",
    creator: "Drawlikeasir",
    categoryName: "Manga, Anatomy",
    description: "",
  },
  ,
  {
    _id: "aLUI7M7MW3",
    title: "How to draw HAIR",
    creator: "Drawlikeasir",
    categoryName: "Manga, Anatomy",
    description: "",
  },
  {
    _id: "aPflB7_XXaY",
    title: "How to DRAW FACES",
    creator: "Drawlikeasir",
    categoryName: "Manga, Anatomy",
    description: "",
  },
  ,
  {
    _id: "aLUI7M7MW3",
    title: "How to draw HAIR",
    creator: "Drawlikeasir",
    categoryName: "Manga, Anatomy",
    description: "",
  },
  {
    _id: "ewMksAbgdBI",
    title: "Sketching Basics + Materials",
    creator: "SchaeferArt",
    categoryName: "Beginner, Pencil Sketch",
    description: "",
  },
  ,
  {
    _id: "nDe7kHa6MVo",
    title: "Simplifying Objects + Learning to See",
    creator: "SchaeferArt",
    categoryName: "Beginner, Pencil Sketch",
    description: "",
  },
  {
    _id: "5Zc1xVS_X7Q",
    title: "Shading Techniques",
    creator: "SchaeferArt",
    categoryName: "Manga, Anatomy",
    description: "",
  },
  ,
  {
    _id: "agir1oR0gc0",
    title: "How to Draw a Tiger",
    creator: "Jon Harris",
    categoryName: "Pencil Sketch",
    description: "",
  },
  {
    _id: "3kojEoKgrTY",
    title: "Easy Watercolor Painting Ideas for Beginners Step by Step",
    creator: "Makoccino",
    categoryName: "Beginner, Watercolor",
    description: "",
  },
  {
    _id: "9P0ot0ifwXk",
    title:
      "Make Your Watercolor Painting Look MAGICAL With These Easy Watercolor Techniques & Ideas!",
    creator: "Makoccino",
    categoryName: "Watercolor",
    description: "",
  },
  ,
  {
    _id: "tDru2siHbaM",
    title: "Watercolor painting process",
    creator: "HamRib Art",
    categoryName: "Watercolor, Portrait",
    description: "",
  },
  {
    _id: "AWvTb69cm24",
    title: "How to improve your drawing RIGHT NOW.",
    creator: "Silvie Mahdal",
    categoryName: "Portrait, Pencil Sketch",
    description: "",
  },
];
